name: Commit Log Backup

on:
  push:
    branches:
      - main

jobs:
  log_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Show Last Commit
        run: git log -1

      - name: Echo Done
        run: echo "✅ 자동화 작동 테스트 성공"
